services:
  nginx:
    container_name: esky-nginx
    image: esky-nginx-image
    build: ./assigment-3
    ports:
      - "8080:80"
      - "9001:9001"
  go-app:
    container_name: esky-go-app
    build: ./assigment-2
    image: esky-go-app-image